// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9wy7fRGv7wyGeFniWuQvPX-4BwEs1hN8',
    appId: '1:689072731299:web:35113ecb3eb1a0ff0efb16',
    messagingSenderId: '689072731299',
    projectId: 'connectme-community',
    authDomain: 'connectme-community.firebaseapp.com',
    storageBucket: 'connectme-community.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRCSmj0jfgijY9fW35VQHCk7yQ1_ltm8Q',
    appId: '1:689072731299:android:ae9f6250a8fd93b30efb16',
    messagingSenderId: '689072731299',
    projectId: 'connectme-community',
    storageBucket: 'connectme-community.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9GSJ0AxxzWWyQgB2yOAV0ifouHKF8PnE',
    appId: '1:689072731299:ios:9ecd0a7a4f8c515a0efb16',
    messagingSenderId: '689072731299',
    projectId: 'connectme-community',
    storageBucket: 'connectme-community.firebasestorage.app',
    iosBundleId: 'com.example.connectmeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9GSJ0AxxzWWyQgB2yOAV0ifouHKF8PnE',
    appId: '1:689072731299:ios:9ecd0a7a4f8c515a0efb16',
    messagingSenderId: '689072731299',
    projectId: 'connectme-community',
    storageBucket: 'connectme-community.firebasestorage.app',
    iosBundleId: 'com.example.connectmeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9wy7fRGv7wyGeFniWuQvPX-4BwEs1hN8',
    appId: '1:689072731299:web:cfb60feea81cd7cb0efb16',
    messagingSenderId: '689072731299',
    projectId: 'connectme-community',
    authDomain: 'connectme-community.firebaseapp.com',
    storageBucket: 'connectme-community.firebasestorage.app',
  );
}
